[ADD] Try to compil with windows and ubuntu

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -87,9 +87,17 @@ jobs:
             exit 1
           }
         
+      - name: Check if pacman exists
+        run: |
+          if (Test-Path "C:\msys64\usr\bin\pacman.exe") {
+            Write-Host "pacman is available."
+          } else {
+            Write-Error "pacman is not found. Check MSYS2 installation."
+            exit 1
+          }
+        
       - name: Update package database and install dependencies
         run: |
-          C:\msys64\usr\bin\bash.exe -c "echo 'Updating package database...'"
           C:\msys64\usr\bin\bash.exe -c "pacman -Sy --noconfirm"
           C:\msys64\usr\bin\bash.exe -c "pacman -S --noconfirm mingw-w64-x86_64-sfml mingw-w64-x86_64-toolchain"
         
@@ -119,6 +127,7 @@ jobs:
               exit /b 1
             )
           )
+
 
 
 
